### ISSUE TITLE
Request for Missing 'functions2' and 'dump' Files in Project

### ISSUE THREAD

**Issue by hitergelei** [Syrocco/local-density-c-python#1]
Hello Syrocco,
  I hope this message finds you well. I am a student from Hunan University in China, and my academic interest is in the development of machine learning potential potential. I am currently researching the use of pybind11 for mixed programming of Python and C++ codes and came across your project.
  I have been trying to study your code, but I noticed that the 'functions2' file and 'dump' file seem to be missing from the repository. These files appear to be essential for understanding the full scope of your work. I was wondering if you could possibly provide these files or point me in the right direction to obtain them.
  It would be greatly appreciated if you could share these files with me. My email address is hjchen@hnu.edu.cn , and I am more than happy to receive them there.

Looking forward to your response.  ^_^

**Comment by Syrocco** [comment]
Hi Hitergelei,
I added the necessary example files to make it work.
Note that it was a "personal code" not well made and especially not to be understood from anyone except me :) .
The .dump file is a data file containing the positions of my particles, functions.py contain a Class that call a parser (in parser.py) to read the positions of my particles. Such that x_vals, y_vals and r_vals are arrays of size N (the number of particles), Lx_vals and Ly_vals are the size of the box in which the particles are. 
Please don't hesitate to ask me if you have any question.
On the pybind side, ChatGPT is very good at converting C++ code to code that can be executed in python through pybind.

**Comment by hitergelei** [comment]
> Hi Hitergelei, I added the necessary example files to make it work. Note that it was a "personal code" not well made and especially not to be understood from anyone except me :) . The .dump file is a data file containing the positions of my particles, functions.py contain a Class that call a parser (in parser.py) to read the positions of my particles. Such that x_vals, y_vals and r_vals are arrays of size N (the number of particles), Lx_vals and Ly_vals are the size of the box in which the particles are. Please don't hesitate to ask me if you have any question. On the pybind side, ChatGPT is very good at converting C++ code to code that can be executed in python through pybind.

Thank you for providing such helpful information. I wish you success in your work and happiness in your life. Hahah~
